services:
  web:
    image: ${DOCKERHUB_USER}/url-shortner:${IMAGE_TAG:-latest}
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_SUPABASE_URL: ${NEXT_PUBLIC_SUPABASE_URL}
        NEXT_PUBLIC_SUPABASE_ANON_KEY: ${NEXT_PUBLIC_SUPABASE_ANON_KEY}
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      HOSTNAME: 0.0.0.0
      PORT: "3000"
